<?xml version="1.0" encoding="utf-8"?><Database Name="fujitsu" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=152.14.106.21;Initial Catalog=fujitsu;User ID=testuser;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="NamespaceRefactorer.Properties.Settings" SettingsPropertyName="fujitsuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sdk_mappings" Member="sdk_mappings">
    <Type Name="sdk_mapping">
      <Column Name="model_identifier" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="old_sdk" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="new_sdk" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>