//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSQLConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class assembly_map
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assembly_map()
        {
            this.sdk_map2 = new HashSet<sdk_map2>();
        }
    
        public int id { get; set; }
        public int sdk_id { get; set; }
        public string old_path { get; set; }
        public string new_path { get; set; }
        public string name { get; set; }
    
        public virtual sdk2 sdk2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sdk_map2> sdk_map2 { get; set; }
    }
}
