//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSQLConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdk_map2
    {
        public int id { get; set; }
        public int sdk_id { get; set; }
        public int namespace_map_id { get; set; }
        public int assembly_map_id { get; set; }
        public string model_identifier { get; set; }
        public string old_classname { get; set; }
        public string new_classname { get; set; }
    
        public virtual assembly_map assembly_map { get; set; }
        public virtual namespace_map namespace_map { get; set; }
        public virtual sdk2 sdk2 { get; set; }
    }
}
